#############################################################################
# Makefile for building: hw5
# Generated by qmake (2.01a) (Qt 4.8.6) on: Fri Oct 28 17:04:30 2016
# Project:  hw5.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile hw5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Bag.cpp \
		Board.cpp \
		Dictionary.cpp \
		getNamesWindow.cpp \
		numPlayersWindow.cpp \
		Player.cpp \
		playScrabble.cpp \
		scrabbleButton.cpp \
		scrabbleWindow.cpp \
		Square.cpp moc_getNamesWindow.cpp \
		moc_numPlayersWindow.cpp \
		moc_scrabbleButton.cpp \
		moc_scrabbleWindow.cpp
OBJECTS       = Bag.o \
		Board.o \
		Dictionary.o \
		getNamesWindow.o \
		numPlayersWindow.o \
		Player.o \
		playScrabble.o \
		scrabbleButton.o \
		scrabbleWindow.o \
		Square.o \
		moc_getNamesWindow.o \
		moc_numPlayersWindow.o \
		moc_scrabbleButton.o \
		moc_scrabbleWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw5.pro
QMAKE_TARGET  = hw5
DESTDIR       = 
TARGET        = hw5

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw5.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile hw5.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hw5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw51.0.0 || $(MKDIR) .tmp/hw51.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw51.0.0/ && $(COPY_FILE) --parents Bag.h Board.h Dictionary.h getNamesWindow.h numPlayersWindow.h Player.h scrabbleButton.h scrabbleWindow.h Square.h Tile.h .tmp/hw51.0.0/ && $(COPY_FILE) --parents Bag.cpp Board.cpp Dictionary.cpp getNamesWindow.cpp numPlayersWindow.cpp Player.cpp playScrabble.cpp scrabbleButton.cpp scrabbleWindow.cpp Square.cpp .tmp/hw51.0.0/ && (cd `dirname .tmp/hw51.0.0` && $(TAR) hw51.0.0.tar hw51.0.0 && $(COMPRESS) hw51.0.0.tar) && $(MOVE) `dirname .tmp/hw51.0.0`/hw51.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw51.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_getNamesWindow.cpp moc_numPlayersWindow.cpp moc_scrabbleButton.cpp moc_scrabbleWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_getNamesWindow.cpp moc_numPlayersWindow.cpp moc_scrabbleButton.cpp moc_scrabbleWindow.cpp
moc_getNamesWindow.cpp: numPlayersWindow.h \
		getNamesWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) getNamesWindow.h -o moc_getNamesWindow.cpp

moc_numPlayersWindow.cpp: numPlayersWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) numPlayersWindow.h -o moc_numPlayersWindow.cpp

moc_scrabbleButton.cpp: scrabbleButton.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) scrabbleButton.h -o moc_scrabbleButton.cpp

moc_scrabbleWindow.cpp: Player.h \
		Tile.h \
		Bag.h \
		scrabbleButton.h \
		Board.h \
		Square.h \
		Dictionary.h \
		scrabbleWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) scrabbleWindow.h -o moc_scrabbleWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Bag.o: Bag.cpp Bag.h \
		Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bag.o Bag.cpp

Board.o: Board.cpp Board.h \
		Tile.h \
		Square.h \
		Dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o Board.cpp

Dictionary.o: Dictionary.cpp Dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dictionary.o Dictionary.cpp

getNamesWindow.o: getNamesWindow.cpp getNamesWindow.h \
		numPlayersWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getNamesWindow.o getNamesWindow.cpp

numPlayersWindow.o: numPlayersWindow.cpp numPlayersWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numPlayersWindow.o numPlayersWindow.cpp

Player.o: Player.cpp Player.h \
		Tile.h \
		Bag.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

playScrabble.o: playScrabble.cpp scrabbleWindow.h \
		Player.h \
		Tile.h \
		Bag.h \
		scrabbleButton.h \
		Board.h \
		Square.h \
		Dictionary.h \
		numPlayersWindow.h \
		getNamesWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playScrabble.o playScrabble.cpp

scrabbleButton.o: scrabbleButton.cpp scrabbleButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scrabbleButton.o scrabbleButton.cpp

scrabbleWindow.o: scrabbleWindow.cpp scrabbleWindow.h \
		Player.h \
		Tile.h \
		Bag.h \
		scrabbleButton.h \
		Board.h \
		Square.h \
		Dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scrabbleWindow.o scrabbleWindow.cpp

Square.o: Square.cpp Square.h \
		Tile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Square.o Square.cpp

moc_getNamesWindow.o: moc_getNamesWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getNamesWindow.o moc_getNamesWindow.cpp

moc_numPlayersWindow.o: moc_numPlayersWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numPlayersWindow.o moc_numPlayersWindow.cpp

moc_scrabbleButton.o: moc_scrabbleButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scrabbleButton.o moc_scrabbleButton.cpp

moc_scrabbleWindow.o: moc_scrabbleWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scrabbleWindow.o moc_scrabbleWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

